-- Chạy trên database SachOnline nếu gặp lỗi đăng ký do vượt độ dài cột (Validation / truncation).
-- Đồng bộ với Model1.edmx (KHACHHANG).

IF COL_LENGTH('dbo.KHACHHANG', 'HoTen') IS NOT NULL
    ALTER TABLE dbo.KHACHHANG ALTER COLUMN HoTen NVARCHAR(100) NOT NULL;
GO
IF COL_LENGTH('dbo.KHACHHANG', 'TaiKhoan') IS NOT NULL
    ALTER TABLE dbo.KHACHHANG ALTER COLUMN TaiKhoan VARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.KHACHHANG', 'Email') IS NOT NULL
    ALTER TABLE dbo.KHACHHANG ALTER COLUMN Email VARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.KHACHHANG', 'DiaChi') IS NOT NULL
    ALTER TABLE dbo.KHACHHANG ALTER COLUMN DiaChi NVARCHAR(200) NULL;
GO
IF COL_LENGTH('dbo.KHACHHANG', 'DienThoai') IS NOT NULL
    ALTER TABLE dbo.KHACHHANG ALTER COLUMN DienThoai VARCHAR(20) NULL;
GO
